
Using device: cuda
Traceback (most recent call last):
  File "/home/inno/DSCM/train.py", line 155, in <module>
    train()
  File "/home/inno/DSCM/train.py", line 55, in train
    premodel1, premodel2, dataset, train_sampler, val_sampler, test_sampler, nj = load_data_weight(premodel1, premodel2, radar)
  File "/home/inno/DSCM/model/function.py", line 100, in load_data_weight
    model2.load_state_dict(torch.load('../weights/autoencoder_range_biliinear.pth'))
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../weights/autoencoder_range_biliinear.pth'